---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    rsyslog_configuration_templates_path: /tmp/rsyslog

  pre_tasks:
    - name: create directory
      file:
        dest: "{{ rsyslog_configuration_templates_path }}"
        mode: '0644'
        state: directory

    - name: populate configuration template
      copy:
        dest: "{{ rsyslog_configuration_templates_path }}/test-app.j2"
        content: |
          if ( $syslogfacility-text == "local6" and $programname == "test-app" ) then {
              action(type="omfile" file="/var/log/test-app.log")
              stop
          }
        mode: '0644'

  roles:
    - role: ansible-role-rsyslog
